language: objective-c
osx_image: xcode61
before_install:
- brew update
- brew unlink xctool
- brew install xctool --HEAD
- xctool -v
- brew install automake
- brew unlink libtool
- brew install libtool
- brew install protobuf
- ./scripts/build.sh
- ./travis/travis.sh
script:
- xctool -project ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj -sdk iphonesimulator -scheme ProtocolBuffers build test
- xctool -project ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj -scheme "ProtocolBuffers(OSX)" build test
